# NumPy Overview
NumPy or numpy is a Linear Algebra Library for Python, a lot of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

NumPy arrarys come in flavors 1D vectors or 2D matrices.

## NumPy Arrays
### Creating Arrays
#### Via Type Casting

In [1]:
import numpy as np

In [2]:
my_list = [1, 2 , 3] # python list
np_arr = np.array(my_list) # casting python list to an array
np_arr # retruns 1D array

array([1, 2, 3])

In [3]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Via NumPy Array Generating functions

In [4]:
np.arange(start=0,stop=9,step=2) # returns an array of evenly space integer values in given range

array([0, 2, 4, 6, 8])

In [5]:
np.zeros(shape=3) # returns a 1D array of zeroes
np.zeros(shape=(3,3)) # returns a 3x3 matrix or 2D array zeros

np.ones(shape=3) # returns a 1D array of ones
np.ones(shape=(3,3)) # returns a 3x3 matrix or 2D array ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.linspace(start=0, stop=10, num=20) # returns array of evenly spaced numbers in the gievn range

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [7]:
np.eye(N=4) # returns a N by N identity matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.random.rand(5) # returns a 1D array of with random values between 0 and 1
np.random.rand(5, 5) # returns a 2D array of with random values

array([[0.3851829 , 0.12339246, 0.84789492, 0.54687184, 0.41140759],
       [0.63494661, 0.74584952, 0.75713661, 0.59973376, 0.97700955],
       [0.05251514, 0.41129385, 0.64422917, 0.56411716, 0.89159623],
       [0.63598153, 0.29893586, 0.36491419, 0.22651927, 0.90443905],
       [0.87465178, 0.25959887, 0.25819801, 0.2270764 , 0.65279841]])

In [9]:
np.random.randn(5) # returns 1D array random numbers from the standard normal distribution centered around zero
np.random.randn(5, 5) # returns 2D array random numbers from the standard normal distribution centered around zero

array([[ 0.60271241, -0.15029335,  0.37494505,  1.80626925, -0.79511961],
       [-0.07241092, -0.54795351, -0.11172245, -0.45172205, -1.12212179],
       [ 0.00822262, -0.33121283,  1.33188682,  0.81981222, -0.58816773],
       [-1.81826013,  0.77850165,  1.06208436, -0.33017141, -1.78288629],
       [-1.48555672, -2.11481164, -0.9372634 , -0.55625591,  0.77074788]])

In [10]:
np.random.randint(low=0, high=10, size=5) # returns an array of random integers excluding the high argrument

array([3, 6, 8, 6, 5])

### Other Useful methods

In [11]:
np_arr.max() # returns largest value in the array
np_arr.argmax() # returns the index of the largest value

np_arr.min() # returns smallest value in the array
np_arr.argmin() # returns the index of the smallest value

0

In [12]:
np_arr.shape # returns shape of the array
np_arr.dtype # return the data type in the array

dtype('int32')

### NumPy Indexing and Selection

#### 1D Arrays

In [13]:
arr = np.arange(0,11)
arr[5] # return the value at index eight
arr[1:5] # the values between index 1 and five exclusive
arr[:6] # returns the values up to index 6
arr[5:] # return eventhing between index 5
arr[1:5] = 5 # sets the values between 1 and five exclusive into 5s

# In python everything is a passed by reference, if you want to make a copy of an array you need the following
second_arr = arr.copy()

#### 2D Arrays

In [14]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_2d[1] # returns the second row
arr_2d[1][1] # returns the value in the second column in the second row
arr_2d[1,1] # returns the value in the second column in the second row
arr_2d[:2, 1:] # returns the values in the first two rows and from the second column onwards

array([[2, 3],
       [5, 6]])

#### Conditional Selection

In [15]:
bool_arr = arr > 5 # creates a boolean array using a comparsion operator
bool_arr
arr[bool_arr] # Conditional selects all the values that are true in the boolean array
arr[arr>5] # The shorthand

array([ 6,  7,  8,  9, 10])

#### Slicing 2D Array Example

In [16]:
arr_2d = np.arange(50)
arr_2d = arr_2d.reshape(5,10) # reshapes the array for 1D to a 5x10 2D array. Can't reshape to less or more than what you have

In [17]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [18]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

### NumPy Operations

In [19]:
[1,2,3] + [4,5,6] # When you add two lists, the 2nd one gets appended to the first
arr = np.arange(0,11)
arr + arr # Adding to np.arrays adds the values of both arrays together
arr - arr # Subtracts the values in both arrays
arr * arr # Multiplies the values in both arrays

arr + 100 # Scalar (number) operation, adds 100 to all the elements in the array
arr * 5 # Multiplies 5 to all the elements in the array
arr - 5 # Subtracts 5 to all the elements in the array
arr / 5 # Divides 5 to all the elements in the array
arr ** 2 # All the elements in the array to the power of two

# NumPy gives you warnings and output NAN or INF when you try to do illegal math operations
arr / arr # Divides the values in both arrays, first value is NAN

C:\Users\mokay\AppData\Local\Temp\ipykernel_12808\2753033166.py:14: RuntimeWarning: invalid value encountered in divide
  arr / arr # Divides the values in both arrays, first value is NAN


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Some of the Universal NumPy Functions
For more go to [the site docs](https://docs.scipy.org/doc/numpy-1.3.x/reference/ufuncs.html)

In [20]:
np.sqrt(arr) # returns an array of the square roots of every element in the array
np.exp(arr) # returns an array of the expontial of every element in the array
np.max(arr) # returns largest value
np.sin(arr) # passes all the values in the sine function
np.log(arr) # passes all the values in the log function

C:\Users\mokay\AppData\Local\Temp\ipykernel_12808\2696486501.py:5: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # passes all the values in the log function


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])